package com.personaltracker.data.local.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Manages the hardware-isolated Android Keystore master key and AES-256-GCM
 * cryptographic operations for Personal-Tracker v1.
 *
 * Implements ARCH-2, NFR-4, and Story 1.2 specifications.
 */
@Singleton
class SecurityKeyStoreManager @Inject constructor() {

    companion object {
        const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        const val MASTER_KEY_ALIAS = "PersonalTracker_MasterDB_Key"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_TAG_LENGTH_BITS = 128
        private const val KEY_SIZE_BITS = 256
    }

    private val keyStore: KeyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply {
        load(null)
    }

    /**
     * Retrieves the existing Master SecretKey from Android Keystore or generates a new one.
     *
     * If the master key alias exists but cannot be loaded as a valid [KeyStore.SecretKeyEntry],
     * an [IllegalStateException] is thrown rather than overwriting the key, protecting existing data.
     */
    @Synchronized
    fun getOrCreateMasterKey(): SecretKey {
        if (keyStore.containsAlias(MASTER_KEY_ALIAS)) {
            val entry = keyStore.getEntry(MASTER_KEY_ALIAS, null) as? KeyStore.SecretKeyEntry
            if (entry != null) {
                return entry.secretKey
            } else {
                throw IllegalStateException(
                    "Keystore alias '$MASTER_KEY_ALIAS' exists but could not be loaded as SecretKeyEntry."
                )
            }
        }

        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            KEYSTORE_PROVIDER
        )

        val keyGenParameterSpec = KeyGenParameterSpec.Builder(
            MASTER_KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            .setUserAuthenticationRequired(false) // Mandatory for background alarm & exact notification execution
            .setRandomizedEncryptionRequired(true) // Enforces unique random IV generated by crypto provider per encryption
            .build()

        keyGenerator.init(keyGenParameterSpec)
        return keyGenerator.generateKey()
    }

    /**
     * Encrypts plaintext bytes using the Keystore Master Key via AES-256-GCM.
     *
     * Note: Performs synchronous Keystore I/O. Callers should invoke off the main thread where appropriate.
     *
     * @param plaintext Raw bytes to encrypt.
     * @return [EncryptedPayload] containing the 12-byte IV and ciphertext with 128-bit authentication tag.
     */
    fun encrypt(plaintext: ByteArray): EncryptedPayload {
        val masterKey = getOrCreateMasterKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, masterKey)
        val ciphertext = cipher.doFinal(plaintext)
        val iv = cipher.iv ?: throw IllegalStateException("Cipher IV must not be null after initialization.")
        return EncryptedPayload(iv = iv, ciphertext = ciphertext)
    }

    /**
     * Decrypts an [EncryptedPayload] using the Keystore Master Key via AES-256-GCM.
     *
     * Note: Performs synchronous Keystore I/O. Callers should invoke off the main thread where appropriate.
     *
     * @param encryptedPayload [EncryptedPayload] containing IV and ciphertext.
     * @return Decrypted plaintext bytes.
     * @throws AEADBadTagException if ciphertext or tag was tampered with.
     * @throws KeyPermanentlyInvalidatedException if Keystore master key was invalidated.
     */
    fun decrypt(encryptedPayload: EncryptedPayload): ByteArray {
        val masterKey = getOrCreateMasterKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, encryptedPayload.iv)
        cipher.init(Cipher.DECRYPT_MODE, masterKey, spec)
        return cipher.doFinal(encryptedPayload.ciphertext)
    }
}
